/* ============================================================================
   views.js  ·  the eleven screens

   Every screen renders from a payload the server assembled. There is no seed
   data in this file, no arithmetic on a duration, and no state change. A button
   that changes something calls E, which asks the server, and then the screen
   reloads from whatever the server says is true afterwards. If the server
   refuses, the refusal is what appears.

   The colour vocabulary is unchanged and there is nothing new in it:
     purple  the agent
     blue    a person
     slate   deterministic software
     amber   a wait nobody owns
   Green is not an owner and is used only where something genuinely finished.
   ============================================================================ */

window.VIEWS = (function () {
  'use strict';

  var el = M.el, card = UI.card, metric = UI.metric, chip = UI.chip, btn = UI.btn;

  function sheet(o) { if (window.App) window.App.sheet(o); }
  function go(route) { if (window.App) window.App.go(route); }
  function toast(msg, kind, ms) { M.toast(msg, kind || 'agent', ms || 2600); }

  /* ------------------------------------------------------------- helpers -- */

  /** A bordered strip of numbers. One border instead of four. */
  function stats(items) { return el('div.stats', null, items.filter(Boolean)); }

  /** Label left, tabular number right, hairline between rows. */
  function deflist(rows) {
    var dl = el('dl.deflist');
    rows.filter(Boolean).forEach(function (r) {
      dl.appendChild(el('dt', null, r[0]));
      dl.appendChild(el('dd' + (r[2] ? '.' + r[2] : ''), null, r[1]));
    });
    return dl;
  }

  /** Owner is the whole colour system, so it is always a chip and never a word. */
  function ownerChip(owner) { return UI.ownerChip(owner); }

  var TONE_FOR_OWNER = { agent: 'agent', human: 'accent', system: 'system', clock: 'clock' };

  function stateChip(b) {
    var kind = b.actability === 'external' ? 'own-clock'
      : b.actability === 'person' ? 'own-human'
      : (b.owner === 'agent' ? 'own-agent' : 'own-system');
    return chip(b.stateLabel, kind, true);
  }

  function recChip(rec, conf) {
    if (!rec) return chip('Not screened', 'is-plain');
    var map = { advance: '', review: 'is-warn', insufficient_evidence: 'is-warn' };
    var label = { advance: 'Advance', review: 'Review', insufficient_evidence: 'Not enough said' }[rec] || rec;
    return chip(label + (conf != null ? ' · ' + Math.round(conf * 100) + '%' : ''), map[rec] || 'is-plain');
  }

  /**
   * The line that has to appear next to every evaluation. A deterministic
   * rubric is a real feature and it is not a model, so it never gets to look
   * like one.
   */
  function evalProvenance(meta) {
    if (!meta) return null;
    if (meta.mode === 'human') return el('div.small.faint', null, meta.note);
    if (meta.isModel) {
      return el('div.small.faint', null,
        'Generated by ' + meta.model + ', prompt ' + meta.promptVersion + ', ' + meta.latencyMs + ' ms.');
    }
    return el('div.sim-note', null, [
      el('b', null, 'No model ran. '),
      'This evaluation is a deterministic match against the phrase bank the store owns. ' +
      'Set LLM_API_KEY and run the screening again to use a model.'
    ]);
  }

  function personRow(b, opts) {
    opts = opts || {};
    return el('button.qitem' + (opts.cls ? '.' + opts.cls : ''), {
      type: 'button',
      onclick: opts.onClick || function () { openCandidate(b.applicationId); }
    }, [
      UI.avatar(b.initials, opts.avatarKind),
      el('div.qmain', null, [
        el('div.qname', null, b.name),
        el('div.qsub', null, opts.sub || (b.role + ' · ' + b.store))
      ]),
      opts.right || el('div.row', { style: { gap: '6px', alignItems: 'center' } }, [
        opts.chipNode || stateChip(b),
        el('span.small.mono.faint', null, E.coarse(b.waitingMs))
      ])
    ]);
  }

  function openCandidate(applicationId) {
    E.ui.focusApplication = applicationId;
    go('candidate');
  }

  function refusalToast(r) {
    if (r.ok) return true;
    toast('<b>Refused.</b> ' + (r.reason || r.error || 'The server would not do that.'), 'crit', 6000);
    return false;
  }

  function actThen(promise, okMsg) {
    return promise.then(function (r) {
      if (!refusalToast(r)) { E.refresh(); return r; }
      if (okMsg) toast(okMsg, 'good', 2600);
      E.refresh();
      return r;
    });
  }

  function emptyIf(list, title, sub) {
    return list && list.length ? null : UI.empty(title, sub);
  }

  /* ==================================================================== deck */

  function deck() {
    var d = E.data();
    var o = d.overnight;
    var q = d.queue;

    var wrap = el('div.col');

    wrap.appendChild(el('div.col.tight', null, [
      el('h2.h1', null, E.fmtDay(E.now()) + ', ' + E.fmtDateTime(E.now()).split(', ')[1]),
      el('div.small.muted', null, 'Everything that arrived over the weekend, and what is left for you')
    ]));

    /* Colour here means owner, not decoration. Purple is the agent, blue is a
       person. The other two are counts nobody owns, so they stay plain. */
    wrap.appendChild(stats([
      metric({ value: o.received, label: 'Applications received',
               sub: 'Since ' + E.fmtDateTime(o.windowStartAt) }),
      metric({ value: o.autoAdvanced, label: 'Screened, no human review',
               sub: 'Rules and the screening agent', tone: 'agent' }),
      metric({ value: q.needsPerson.length, label: 'Waiting on a person',
               sub: 'Across every stage', tone: 'accent' }),
      metric({ value: q.waitingExternal.length, label: 'Waiting on somebody outside',
               sub: 'Candidates, agencies, government', tone: 'clock' })
    ]));

    if (q.over48h) {
      wrap.appendChild(el('div.sim-note', null, [
        el('b', null, q.over48h + ' open ' + (q.over48h === 1 ? 'application has' : 'applications have') +
          ' been in the same state longer than 48 hours. '),
        'Measured from the recorded state change, not estimated.'
      ]));
    }

    wrap.appendChild(card({
      eyebrow: 'Your queue', title: q.needsPerson.length + ' waiting on you',
      sub: 'Longest wait first. Nothing here moves without a person.',
      flush: true,
      body: q.needsPerson.length
        ? el('div.qlist', null, q.needsPerson.slice(0, 9).map(function (b) {
            return personRow(b, {
              cls: b.blockedBy ? 'is-crit' : 'own-human',
              sub: b.blockedBy || (b.role + ' · ' + b.store),
              chipNode: b.blockedBy ? chip('Blocked', 'is-crit') : stateChip(b)
            });
          }))
        : UI.empty('Nothing is waiting on you', 'Everything open is either moving by itself or waiting on somebody outside.'),
      foot: q.needsPerson.length > 9 ? (q.needsPerson.length - 9) + ' more, on the approvals and exceptions screens.' : null
    }));

    wrap.appendChild(el('div.grid.c2', null, [
      card({
        eyebrow: 'Waiting on somebody outside', title: q.waitingExternal.length + ' we cannot move',
        sub: 'Not a product failure and not drawn as one.',
        flush: true,
        body: q.waitingExternal.length
          ? el('div.qlist', null, q.waitingExternal.slice(0, 6).map(function (b) {
              return personRow(b, { cls: 'own-clock',
                sub: 'Waiting on ' + (b.waitingOn || 'an external system'),
                chipNode: chip(b.stateLabel, 'own-clock', true) });
            }))
          : UI.empty('Nothing is stuck outside')
      }),
      card({
        eyebrow: 'Moving by itself', title: q.productMoving.length + ' the product is handling',
        sub: 'No queue in front of anybody.',
        flush: true,
        body: q.productMoving.length
          ? el('div.qlist', null, q.productMoving.slice(0, 6).map(function (b) {
              return personRow(b, { cls: b.owner === 'agent' ? 'own-agent' : 'own-system' });
            }))
          : UI.empty('Nothing in flight')
      })
    ]));

    var m = d.metrics;
    wrap.appendChild(card({
      eyebrow: 'Measured, not asserted', title: 'What this store group is actually taking',
      sub: 'Every figure computed from recorded events. n is on each one, because a median of two is not a median.',
      body: deflist([
        ['Application to offer', span(m.spans.applicationToOffer)],
        ['Offer to acceptance', span(m.spans.offerToAcceptance)],
        ['Acceptance to first shift', span(m.spans.acceptanceToFirstShift)],
        ['Application to first shift', span(m.spans.applicationToFirstShift)],
        ['Of all elapsed time, spent queued', E.pct(m.queue.queueShare * 100)],
        ['Handoffs per application, median', m.handoffs.median == null ? '--' : m.handoffs.median],
        ['People involved per application, median', m.peopleInvolved.median == null ? '--' : m.peopleInvolved.median]
      ]),
      foot: 'Open Reports for the whole picture, including which step loses the most time.'
    }));

    return wrap;
  }

  function span(s) {
    if (!s || s.median == null) return 'not measurable yet';
    return E.dur(s.median) + '  (n=' + s.n + ')';
  }

  /* ================================================================== decide */

  function decide() {
    var d = E.data();
    var wrap = el('div.col');

    wrap.appendChild(card({
      eyebrow: 'Automation limits', title: 'What the agent may and may not do here',
      body: UI.boundary(d.boundary.agentDoes, d.boundary.humanDoes),
      foot: d.boundary.software
    }));

    if (!d.candidates.length) {
      wrap.appendChild(UI.empty('Nobody is waiting on a decision', 'When a screening finishes, whoever it was appears here.'));
      return wrap;
    }

    wrap.appendChild(card({
      eyebrow: 'Awaiting decision', title: d.count + ' candidates', flush: true,
      sub: 'Longest wait first. Approving or rejecting is recorded against your name.',
      body: el('div.col', { style: { gap: 0 } }, d.candidates.map(decisionRow))
    }));
    return wrap;
  }

  function decisionRow(c) {
    var row = el('div.qitem.own-human', { style: { cursor: 'default' } }, [
      UI.avatar(c.initials),
      el('div.qmain', null, [
        el('div.qname', null, [c.name, c.rehire ? chip('Worked here before', 'is-plain') : null]),
        el('div.qsub', null, c.role + ' · ' + c.store + ' · applied ' + E.fmtDateTime(c.appliedAt) + ' via ' + c.source),
        el('div.row.wrap', { style: { gap: '6px', marginTop: '6px' } }, [
          recChip(c.recommendation, c.confidence),
          c.screening && c.screening.meta && !c.screening.meta.isModel
            ? chip('No model ran', 'is-plain') : null,
          c.interview && c.interview.status === 'complete' ? chip('Manager interview done', 'is-plain') : null,
          chip('Waiting ' + E.coarse(c.waitingMs), 'is-plain')
        ])
      ]),
      el('div.row', { style: { gap: '6px' } }, [
        btn('Evidence', { cls: 'is-ghost is-sm', onClick: function () { openEvidence(c); } }),
        btn('Reject', { cls: 'is-ghost is-sm', onClick: function () { decideOn(c, 'REJECTED'); } }),
        btn('Approve', { cls: 'is-primary is-sm', onClick: function () { decideOn(c, 'APPROVED'); } })
      ])
    ]);
    return row;
  }

  function decideOn(c, state) {
    var isApprove = state === 'APPROVED';
    sheet({
      eyebrow: isApprove ? 'Hire decision' : 'Reject',
      title: (isApprove ? 'Approve ' : 'Reject ') + c.name + '?',
      body: el('div.col', null, [
        el('p.small', null, isApprove
          ? 'This is recorded against ' + E.person().name + ' with the reason you give. An offer is generated straight afterwards and is not sent until you confirm that separately.'
          : 'This ends the application. It is recorded against ' + E.person().name + ' with the reason you give.'),
        c.recommendation ? el('div.sim-note', null, [
          el('b', null, 'The evaluation said ' + c.recommendation.replace(/_/g, ' ') + '. '),
          'It is evidence, not a decision. Overriding it is normal and the override is recorded next to it.'
        ]) : null,
        el('label.col.tight', null, [
          UI.eyebrow('Reason'),
          el('textarea.ch-input', { rows: 3, id: 'decide-reason', style: { width: '100%', minHeight: '76px' },
            placeholder: isApprove ? 'Why this person, in your words' : 'Why not, in your words' })
        ]),
        el('div.row', { style: { gap: '8px', marginTop: 'var(--s4)' } }, [
          btn(isApprove ? 'Approve, and record it against me' : 'Reject, and record it against me', {
            cls: isApprove ? 'is-primary' : 'is-crit',
            onClick: function () {
              var reason = (document.getElementById('decide-reason') || {}).value || null;
              window.App.closeSheet();
              actThen(E.transition(c.applicationId, state, { reason: reason, workMs: 45000 }),
                c.name + ' ' + (isApprove ? 'approved' : 'rejected') + '. It is on the audit trail.');
            }
          }),
          btn('Cancel', { cls: 'is-ghost', onClick: function () { window.App.closeSheet(); } })
        ])
      ])
    });
  }

  function openEvidence(c) {
    var s = c.screening;
    sheet({
      eyebrow: 'Screening evidence', title: c.name,
      body: el('div.col', null, [
        s ? card({
          eyebrow: 'Recommendation', title: s.evaluation.summary,
          body: el('div.col.tight', null, [
            el('div.row.wrap', { style: { gap: '6px' } }, [
              recChip(s.evaluation.recommendation, s.evaluation.confidence),
              chip('Conversation ' + E.dur(s.durationMs), 'is-plain'),
              chip(s.transcriptTurns + ' turns', 'is-plain')
            ]),
            evalProvenance(s.meta)
          ]),
          foot: s.evaluation.recommendedNextAction
        }) : UI.empty('No screening on file'),
        s ? criteriaTable(s.evaluation) : null,
        c.eligibility ? eligibilityCard(c.eligibility) : null,
        c.rehire ? rehireCard(c.rehire) : null,
        btn('Open the full record', { cls: 'is-ghost', onClick: function () {
          window.App.closeSheet(); openCandidate(c.applicationId);
        } })
      ])
    });
  }

  function criteriaTable(ev) {
    var VERDICT = { met: ['Met', 'is-good'], partly_met: ['Partly', 'is-warn'],
                    not_met: ['Not met', 'is-crit'], not_covered: ['Not covered', 'is-plain'] };
    return card({
      eyebrow: 'Criterion by criterion', title: 'Every verdict quotes what was said',
      flush: true,
      body: el('div.tw', null, el('table.t', null, [
        el('thead', null, el('tr', null, [
          el('th', null, 'Criterion'), el('th', null, 'Verdict'), el('th', null, 'What they said')
        ])),
        el('tbody', null, ev.criteria.map(function (c) {
          var v = VERDICT[c.verdict] || [c.verdict, 'is-plain'];
          return el('tr', null, [
            el('td', null, c.key.replace(/_/g, ' ')),
            el('td', null, chip(v[0], v[1])),
            el('td.small.muted', null, c.evidence
              ? '"' + c.evidence + '"'
              : (c.note || 'Not covered in the conversation.'))
          ]);
        }))
      ])),
      foot: (ev.concerns.length ? ev.concerns.length + ' concern' + (ev.concerns.length === 1 ? '' : 's') + ' raised. ' : '') +
            (ev.unansweredQuestions.length ? ev.unansweredQuestions.length + ' question' +
              (ev.unansweredQuestions.length === 1 ? '' : 's') + ' went unanswered.' : 'Every question was answered.')
    });
  }

  function eligibilityCard(e) {
    return card({
      eyebrow: 'Eligibility', title: 'Deterministic rules, ' + e.version,
      sub: 'No model runs on this. Age, right to work and availability are yes or no questions against values we already hold.',
      flush: true,
      body: el('div.col', { style: { gap: 0 } }, e.results.map(function (r) {
        return el('div.qitem', { style: { cursor: 'default', gridTemplateColumns: '20px minmax(0,1fr) auto' } }, [
          el('span.dot', { style: { background: r.passed ? 'var(--good)' : 'var(--crit)', width: '8px', height: '8px', borderRadius: '50%' } }),
          el('div.qmain', null, [
            el('div.qname', { style: { fontSize: 'var(--t-small)' } }, r.name),
            el('div.qsub', null, r.basis),
            r.law ? el('div.small.faint', null, r.law) : null
          ]),
          chip(r.passed ? 'Pass' : (r.advisory ? 'Advisory' : 'Fail'),
               r.passed ? 'is-good' : (r.advisory ? 'is-plain' : 'is-crit'))
        ]);
      }))
    });
  }

  function rehireCard(rehire) {
    return card({
      eyebrow: 'Rehire', title: 'Matched this retailer\'s own employment records',
      sub: rehire.scope,
      body: el('div.col.tight', null, [
        deflist([
          ['Previous role', rehire.record.role + ', ' + rehire.record.storeName],
          ['Employed', rehire.record.startedOn.slice(0, 10) + ' to ' + rehire.record.separatedOn.slice(0, 10)],
          ['Employee ID', rehire.record.employeeId],
          ['Eligible for rehire', rehire.rehireEligible ? 'Yes' : 'No'],
          ['Match confidence', rehire.confidence === 'exact' ? 'Exact' : 'Partial, a person should confirm'],
          ['Form I-9 reuse', rehire.i9.reusable ? 'Inside the three-year window' : 'Outside the window, a new form is needed']
        ]),
        el('div.small.faint', null, rehire.i9.rule),
        el('div.small', null, rehire.i9.effect),
        rehire.reusable && rehire.reusable.length ? el('div.col.tight', null, [
          UI.eyebrow('What does not have to be done twice'),
          el('div.tw', null, el('table.t', null, [
            el('thead', null, el('tr', null, [el('th', null, 'Item'), el('th', null, 'Reuse'), el('th', null, 'Why')])),
            el('tbody', null, rehire.reusable.map(function (r) {
              return el('tr', null, [
                el('td', null, r.name),
                el('td', null, chip(r.reuse.replace(/-/g, ' '), r.reuse === 'never' ? 'is-crit' : (r.reuse === 'retake' || r.reuse === 'fresh-order' ? 'is-warn' : 'is-good'))),
                el('td.small.muted', null, r.why)
              ]);
            }))
          ]))
        ]) : null
      ])
    });
  }

  /* =============================================================== screening */

  function screening() {
    var d = E.data();
    var wrap = el('div.col');

    wrap.appendChild(stats([
      metric({ value: d.queue.completed.length, label: 'Screened', sub: 'Evaluation on file', tone: 'agent' }),
      metric({ value: d.queue.waiting.length, label: 'Waiting for a screening', sub: 'Eligible, not yet run' }),
      metric({ value: d.queue.completed.filter(function (c) { return c.isModel; }).length,
               label: 'Evaluated by a model', sub: E.llm() && E.llm().configured ? E.llm().model : 'No key configured', tone: 'agent' }),
      metric({ value: d.queue.completed.filter(function (c) { return c.recommendation !== 'advance'; }).length,
               label: 'The agent would not advance', sub: 'A person reads these', tone: 'accent' })
    ]));

    if (!E.llm().configured) {
      wrap.appendChild(el('div.sim-note', null, [
        el('b', null, 'No LLM_API_KEY is set. '),
        E.llm().note.replace('No LLM_API_KEY is set. ', '') +
        ' Set one in demo/server/.env and run a screening again to use a model. Nothing else about the product changes.'
      ]));
    }

    if (d.queue.waiting.length) {
      wrap.appendChild(card({
        eyebrow: 'Waiting', title: d.queue.waiting.length + ' eligible, not yet screened',
        sub: 'Running a screening sends the transcript to whichever model is configured.',
        flush: true,
        body: el('div.qlist', null, d.queue.waiting.map(function (b) {
          return el('div.qitem.own-agent', { style: { cursor: 'default' } }, [
            UI.avatar(b.initials, 'agent'),
            el('div.qmain', null, [
              el('div.qname', null, b.name),
              el('div.qsub', null, b.role + ' · ' + b.store + ' · waiting ' + E.coarse(b.waitingMs))
            ]),
            btn('Run the screening', { cls: 'is-agent is-sm', onClick: function (e) {
              var b2 = e && e.currentTarget;
              if (b2) { b2.disabled = true; b2.textContent = 'Running'; }
              E.runScreening(b.applicationId).then(function (r) {
                if (!r.ok) { toast('<b>Refused.</b> ' + (r.error || ''), 'crit', 5000); return E.refresh(); }
                var ev = (r.results || []).filter(function (x) { return x.evaluation; })[0];
                toast(ev
                  ? 'Screened. Recommendation: <b>' + ev.evaluation.recommendation.replace(/_/g, ' ') + '</b>' +
                    (ev.meta.isModel ? ' from ' + ev.meta.model : ', from the phrase bank rubric. No model ran.')
                  : 'Screening complete.', 'agent', 5200);
                return E.refresh();
              });
            } })
          ]);
        }))
      }));
    }

    var det = d.detail;
    if (det) {
      var s = det.screening;
      wrap.appendChild(card({
        eyebrow: 'Transcript', title: det.candidate.name + ', ' + E.dur(s.durationMs) + ' conversation',
        sub: s.channel === 'voice'
          ? 'Voice. The outbound call is an interface here rather than a running integration, and the transcript is what the evaluation reads.'
          : 'In person, notes taken by the manager.',
        flush: true,
        body: el('div.turns', null, s.transcript.map(function (t) {
          var isAgent = t.speaker === 'Agent';
          return el('div.turn' + (isAgent ? '.is-agent' : ''), null, [
            el('div.turn-who', null, isAgent ? 'Agent' : t.speaker),
            el('div.turn-txt', null, t.text)
          ]);
        }))
      }));

      if (s.evaluation) {
        wrap.appendChild(card({
          eyebrow: 'Evaluation', title: s.evaluation.summary,
          body: el('div.col.tight', null, [
            el('div.row.wrap', { style: { gap: '6px' } }, [
              recChip(s.evaluation.recommendation, s.evaluation.confidence),
              chip('Next: ' + s.evaluation.recommendedNextAction, 'is-plain')
            ]),
            evalProvenance(s.evaluationMeta)
          ])
        }));
        wrap.appendChild(criteriaTable(s.evaluation));

        if (s.evaluation.concerns.length) {
          wrap.appendChild(card({
            eyebrow: 'Concerns', title: s.evaluation.concerns.length + ' raised', flush: true,
            body: el('div.qlist', null, s.evaluation.concerns.map(function (c) {
              return el('div.qitem' + (c.severity === 'high' ? '.is-crit' : '.is-warn'),
                { style: { cursor: 'default', gridTemplateColumns: 'minmax(0,1fr) auto' } }, [
                el('div.qmain', null, [
                  el('div.qname', { style: { fontSize: 'var(--t-small)' } }, c.concern),
                  el('div.qsub', null, '"' + c.evidence + '"')
                ]),
                chip(c.severity, c.severity === 'high' ? 'is-crit' : 'is-warn')
              ]);
            }))
          }));
        }
      } else if (s.evaluationError) {
        wrap.appendChild(card({
          eyebrow: 'Evaluation failed', title: 'The model call did not complete',
          body: el('div.col.tight', null, [
            el('div.ch-refuse', null, s.evaluationError),
            el('p.small', null, 'Nothing was written to the candidate record beyond this error. Read the transcript and decide without it, or run it again.')
          ])
        }));
      }

      if (det.llmCall) {
        wrap.appendChild(card({
          eyebrow: 'Audit', title: 'What was sent and what came back',
          sub: 'Chain of thought is neither requested nor stored. The evaluation, its evidence and its confidence are.',
          body: deflist([
            ['Mode', det.llmCall.mode],
            ['Provider', det.llmCall.provider],
            ['Model', det.llmCall.model || 'none'],
            ['Prompt version', det.llmCall.promptVersion],
            ['Latency', det.llmCall.latencyMs + ' ms'],
            ['Transcript turns sent', String(det.llmCall.inputRefs.transcriptTurns)],
            ['Recommendation stored', det.llmCall.recommendation || '--'],
            ['Confidence stored', det.llmCall.confidence != null ? Math.round(det.llmCall.confidence * 100) + '%' : '--'],
            ['Error', det.llmCall.error || 'none']
          ])
        }));
      }

      wrap.appendChild(card({
        eyebrow: 'The phrase bank', title: 'The questions and the phrases the store owns',
        sub: 'Editable by the customer. This is what the deterministic rubric matches against, and what a model is told the criteria are.',
        flush: true,
        body: el('div.tw', null, el('table.t', null, [
          el('thead', null, el('tr', null, [el('th', null, 'Question'), el('th', null, 'Criterion'), el('th', null, 'Concern phrases')])),
          el('tbody', null, det.requisition.questions.map(function (q) {
            return el('tr', null, [
              el('td.small', null, q.text),
              el('td', null, chip(q.criterion.replace(/_/g, ' '), 'is-plain')),
              el('td.small.muted', null, (q.concernPhrases || []).join(', ') || 'none')
            ]);
          }))
        ]))
      }));
    }

    wrap.appendChild(card({
      eyebrow: 'Automation limits', title: 'What the agent may and may not do here',
      body: UI.boundary(d.boundary.agentDoes, d.boundary.humanDoes),
      foot: 'Why eligibility uses rules rather than a model: ' + d.whyRules
    }));

    return wrap;
  }

  /* ================================================================ pipeline */

  function pipeline() {
    var d = E.data();
    var wrap = el('div.col');

    /* Each number wears the colour of the thing that owns it, so this strip
       is the legend for the table underneath it. */
    wrap.appendChild(stats([
      metric({ value: d.ownerTotals.system, label: 'Automated by rules', sub: 'No judgement in them', tone: 'system' }),
      metric({ value: d.ownerTotals.agent, label: 'Handled by the agent', sub: 'Where a rules engine cannot', tone: 'agent' }),
      metric({ value: d.ownerTotals.human, label: 'Require a named person', sub: 'The product will not proceed without one', tone: 'accent' }),
      metric({ value: d.ownerTotals.clock, label: 'Fixed waits', sub: 'Nobody can compress these', tone: 'clock' })
    ]));

    wrap.appendChild(card({
      eyebrow: 'Live', title: E.n(d.inFlight) + ' candidates in progress',
      sub: 'Entered and dropped are counted from recorded events. Median is measured across the ones that finished the step.',
      flush: true,
      body: el('div.steps', null, [stepHead()].concat(d.steps.map(stepRow)))
    }));
    return wrap;
  }

  function stepHead() {
    return el('div.step.is-head', null, [
      el('div.step-cell', null, 'Step'),
      el('div.step-cell', null, 'What happens'),
      el('div.step-cell', null, 'Owner'),
      el('div.step-cell', null, 'Here now'),
      el('div.step-cell', null, 'Dropped'),
      el('div.step-cell', null, 'Median in step')
    ]);
  }

  function stepRow(s) {
    return el('button.step.' + E.ownerClass(s.owner), {
      type: 'button', onclick: function () { openStep(s); }
    }, [
      el('div.step-num', null, String(s.n)),
      el('div.step-name', null, [
        s.name,
        s.clock ? el('span.small.faint', null, ' · legal clock') : null
      ]),
      el('div.step-cell', null, ownerChip(s.owner)),
      el('div.step-cell.num', null, s.inFlight ? String(s.inFlight) : el('span.faint', null, '0')),
      el('div.step-cell.num', null, s.lost ? E.pct(s.dropPct) : el('span.faint', null, '--')),
      el('div.step-cell.num.mono', null, s.medianMs == null
        ? el('span.faint', null, 'no data')
        : E.dur(s.medianMs) + (s.n_durations < 3 ? ' (n=' + s.n_durations + ')' : ''))
    ]);
  }

  function openStep(s) {
    sheet({
      eyebrow: 'Step ' + s.n + ' of 20 · ' + s.stage, title: s.name,
      chipNode: ownerChip(s.owner),
      body: el('div.col', null, [
        card({ body: UI.boundary(s.agentDoes, s.humanDoes), foot: s.software }),
        card({
          eyebrow: 'Measured here', title: 'From recorded events only',
          body: deflist([
            ['Applications that reached this step', String(s.entered)],
            ['In this step right now', String(s.inFlight)],
            ['Lost at this step', s.lost + (s.entered ? ' (' + E.pct(s.dropPct) + ')' : '')],
            ['Median time in step', s.medianMs == null ? 'not measurable yet' : E.dur(s.medianMs) + ' (n=' + s.n_durations + ')']
          ])
        }),
        s.law ? card({ eyebrow: 'The legal position', title: 'What the law actually requires',
                       body: el('p.small', null, s.law) }) : null,
        card({ eyebrow: 'The incumbents', title: s.cover === 0 ? 'Neither sells anything here'
                 : (s.cover === 1 ? 'One of the two sells here' : 'Both sell here'),
               body: el('p.small', null, s.coverNote) })
      ])
    });
  }

  /* =============================================================== candidate */

  function candidate() {
    var d = E.data();
    if (!d) return UI.empty('No candidate selected');
    var c = d.candidate, a = d.application;
    var wrap = el('div.col');

    wrap.appendChild(el('div.row.wrap', { style: { gap: 'var(--s3)', alignItems: 'center' } }, [
      UI.avatar(c.initials),
      el('div.col', { style: { gap: 0, flex: '1 1 auto', minWidth: 0 } }, [
        el('h2.h2', null, c.name),
        el('div.small.muted', null, d.requisition.title + ' · ' + d.store.name + ' · applied ' +
          E.fmtDateTime(a.appliedAt) + ' via ' + a.source)
      ]),
      chip(E.stateLabel(a.state), 'own-' + (E.boot().states[a.state] ? E.boot().states[a.state].owner : 'system'), true),
      el('select.btn.is-ghost.is-sm', {
        'aria-label': 'Choose a candidate',
        onchange: function (e) { E.ui.focusApplication = e.target.value; E.refresh(); }
      }, d.roster.map(function (r) {
        return el('option', { value: r.applicationId, selected: r.applicationId === a.id ? 'selected' : null },
          r.name + '  ·  ' + r.stateLabel);
      }))
    ]));

    if (c.persona) wrap.appendChild(el('div.sim-note', null, [el('b', null, 'Demo persona: '), c.persona]));

    var m = d.metrics;
    wrap.appendChild(stats([
      metric({ value: m.elapsedMs / 86400000, dp: 1, unit: 'days', label: 'Since they applied',
               sub: 'Elapsed, measured' }),
      metric({ value: m.queueMs / 86400000, dp: 1, unit: 'days', label: 'Spent in a queue',
               sub: E.pct(m.queueShare * 100) + ' of elapsed', tone: 'clock' }),
      metric({ value: m.workMs / 3600000, dp: 1, unit: 'h', label: 'Actual work done',
               sub: 'Summed from recorded work', tone: 'system' }),
      metric({ value: m.peopleInvolved.length, label: 'People involved',
               sub: m.handoffs + ' handoffs', tone: 'accent' })
    ]));

    wrap.appendChild(timelineCard(d));

    if (d.parallelism) wrap.appendChild(parallelCard(d));
    if (d.check) wrap.appendChild(checkCard(d.check));
    if (d.compliance.clocks.length) wrap.appendChild(clocksCard(d.compliance, c.name));
    if (a.rehire && a.rehire.matched) wrap.appendChild(rehireCard(a.rehire));
    if (a.eligibility) wrap.appendChild(eligibilityCard(a.eligibility));

    if (d.communications.length) {
      wrap.appendChild(card({
        eyebrow: 'Communications', title: d.communications.length + ' messages, every one recorded',
        sub: 'Development adapters. Nothing left this machine, and the record says so rather than a button changing from Send to Sent.',
        flush: true,
        body: el('div.tw', null, el('table.t', null, [
          el('thead', null, el('tr', null, [el('th', null, 'When'), el('th', null, 'Channel'),
            el('th', null, 'To'), el('th', null, 'Template'), el('th', null, 'Status'), el('th', null, 'Provider ref')])),
          el('tbody', null, d.communications.map(function (x) {
            return el('tr', null, [
              el('td.mono.small', null, E.fmtDateTime(x.at)),
              el('td', null, chip(x.channel, 'is-plain')),
              el('td.small', null, x.to),
              el('td.small.muted', null, x.templateId),
              el('td', null, chip(x.status, x.status === 'failed' ? 'is-crit' : (x.status === 'delivered' ? 'is-good' : 'is-plain'))),
              el('td.mono.small.faint', null, x.providerRef || '--')
            ]);
          }))
        ]))
      }));
    }

    wrap.appendChild(nextActionCard(d));
    wrap.appendChild(auditCard(d.audit, d.connectorCalls));
    return wrap;
  }

  function timelineCard(d) {
    var tl = d.timeline;
    var done = tl.steps.filter(function (s) { return s.status === 'done'; }).length;
    return card({
      eyebrow: 'All twenty steps', title: done + ' done, currently at step ' + tl.currentStep,
      sub: 'Including the steps this product does not control. A wait we cannot compress is not drawn as a failure.',
      flush: true,
      body: el('div.tl', null, tl.steps.map(function (s) {
        var cls = '.tl-item.' + E.ownerClass(s.owner) +
          (s.status === 'done' ? '.is-done' : '') + (s.isCurrent ? '.is-now' : '');
        return el('div' + cls, null, [
          el('div.tl-node', null, String(s.n)),
          el('div.tl-bd', null, [
            el('div.tl-top', null, [
              el('span.tl-t', null, s.name),
              el('span.tl-when', null, statusWord(s))
            ]),
            el('div.tl-who', null, [
              ownerChip(s.owner),
              s.actability === 'external' ? chip('Outside our control', 'own-clock') : null,
              s.status === 'done' && s.elapsedMs != null
                ? el('span.small.mono.faint', null, E.dur(s.elapsedMs) +
                    (s.queueMs ? ', ' + E.dur(s.queueMs) + ' of it queued' : ''))
                : null,
              s.isCurrent && s.elapsedMs != null
                ? el('span.small.mono', { style: { color: 'var(--warn)' } }, 'here ' + E.coarse(s.elapsedMs))
                : null
            ]),
            s.blocker ? el('div.tl-note', { style: { color: 'var(--crit)' } }, s.blocker) : null,
            s.notRequiredReason ? el('div.tl-note', null, s.notRequiredReason) : null,
            s.nextAction ? el('div.tl-note', null, s.nextAction) : null,
            s.tasks && s.tasks.length ? taskList(d.application.id, s.tasks) : null
          ])
        ]);
      }))
    });
  }

  function statusWord(s) {
    if (s.status === 'not_required') return 'not required';
    if (s.status === 'done') return 'done ' + E.fmtDate(s.completedAt);
    if (s.status === 'current') return 'here now';
    if (s.status === 'never_reached') return 'never reached';
    return 'not yet';
  }

  function taskList(applicationId, tasks) {
    return el('div.col.tight', { style: { marginTop: '6px' } }, tasks.map(function (t) {
      var tone = t.status === 'done' ? 'is-good' : (t.status === 'blocked' ? 'is-plain' : 'is-warn');
      return el('div.row', { style: { gap: '8px', alignItems: 'center', flexWrap: 'wrap' } }, [
        chip(t.status === 'in_progress' ? 'running' : t.status, tone),
        el('span.small', null, t.name),
        t.owner === 'human' && t.status === 'in_progress'
          ? btn('Mark done', { cls: 'is-ghost is-sm', onClick: function () {
              actThen(E.completeTask(applicationId, t.key && t.id ? t.id : t.id), t.name + ' marked done.');
            } })
          : null,
        t.blockedBy ? el('span.small.faint', null, 'waiting on ' + t.blockedBy) : null,
        t.reusedFrom ? el('span.small', { style: { color: 'var(--good)' } }, 'reused: ' + t.reusedFrom) : null,
        t.law ? el('span.small.faint', null, t.law) : null,
        t.note ? el('span.small.faint', null, t.note) : null
      ]);
    }));
  }

  function parallelCard(p) {
    var par = p.parallelism;
    return card({
      eyebrow: 'Parallel work', title: par.startedTogether + ' of ' + par.totalTasks + ' onboarding tasks started at the same moment',
      sub: 'Everything with no unmet dependency starts on acceptance instead of each team waiting for the one before it.',
      body: el('div.col.tight', null, [
        deflist([
          ['If every task waited for the one before it', E.dur(par.sequentialMs)],
          ['Longest chain of tasks that genuinely depend on each other', E.dur(par.criticalPathMs)],
          ['Difference', E.dur(par.savedMs) + ' (' + E.round1(par.savedPct) + '%)'],
          ['Observed wall clock so far', par.actualMs == null ? 'still running' : E.dur(par.actualMs)]
        ]),
        el('div.small.faint', null, par.actualNote),
        el('div.tw', null, el('table.t', null, [
          el('thead', null, el('tr', null, [el('th', null, 'Task'), el('th', null, 'Owner'),
            el('th', null, 'Waits for'), el('th', null, 'Status')])),
          el('tbody', null, par.tasks.map(function (t) {
            return el('tr', null, [
              el('td.small', null, t.name),
              el('td', null, ownerChip(t.owner)),
              el('td.small.muted', null, t.afterStart
                ? 'the first day of work for pay'
                : (t.needs.length ? t.needs.join(', ') : 'nothing, it started immediately')),
              el('td', null, chip(t.status === 'in_progress' ? 'running' : t.status,
                t.status === 'done' ? 'is-good' : (t.status === 'blocked' ? 'is-plain' : 'is-warn')))
            ]);
          }))
        ]))
      ])
    });
  }

  function nextActionCard(d) {
    var cur = d.timeline.steps.filter(function (s) { return s.isCurrent; })[0];
    var a = d.application;
    var moves = [];

    function move(state, label, cls) {
      moves.push(btn(label, { cls: cls || 'is-ghost is-sm', onClick: function () {
        actThen(E.transition(a.id, state, {}), label + ' done.');
      } }));
    }

    if (a.state === 'OFFER_PENDING') move('OFFER_SENT', 'Send the offer', 'is-primary is-sm');
    if (a.state === 'OFFER_SENT') {
      move('OFFER_ACCEPTED', 'Record acceptance', 'is-primary is-sm');
      move('OFFER_DECLINED', 'Record a decline');
    }
    if (a.state === 'BACKGROUND_CHECK_PENDING') move('BACKGROUND_CHECK_IN_PROGRESS', 'Order the check', 'is-primary is-sm');
    if (a.state === 'READY_FOR_SHIFT') move('FIRST_SHIFT_SCHEDULED', 'Schedule the first shift', 'is-primary is-sm');
    if (a.state === 'FIRST_SHIFT_SCHEDULED') move('STARTED', 'Record that they started', 'is-primary is-sm');
    if (a.state === 'SCREENING_PENDING') {
      moves.push(btn('Run the screening', { cls: 'is-agent is-sm', onClick: function () {
        actThen(E.runScreening(a.id), 'Screening complete.');
      } }));
    }
    if (a.state === 'DECISION_PENDING') {
      moves.push(btn('Open the decision', { cls: 'is-primary is-sm', onClick: function () { go('decide'); } }));
    }

    return card({
      eyebrow: 'What happens next', title: cur ? cur.name : E.stateLabel(a.state),
      sub: cur ? cur.nextAction : null,
      body: el('div.col.tight', null, [
        el('div.row.wrap', { style: { gap: '8px' } }, moves.length ? moves
          : [el('span.small.muted', null, 'Nothing here is ours to move. ' +
              (cur && cur.actability === 'external' ? 'We are waiting on somebody outside.' : ''))]),
        cur && cur.actability === 'external'
          ? el('div.small.faint', null, 'This step is an external wait. Use the clock control in the sidebar to move the simulated present forward and watch it resolve for the real reason.')
          : null
      ])
    });
  }

  function auditCard(entries, connectorCalls) {
    return card({
      eyebrow: 'Audit trail', title: 'Who did what, when, and why',
      sub: entries.length + ' entries. An employment workflow has to answer that months later, to somebody who was not in the room.',
      flush: true,
      body: el('div.tw', null, el('table.t', null, [
        el('thead', null, el('tr', null, [el('th', null, 'When'), el('th', null, 'Action'),
          el('th', null, 'Who'), el('th', null, 'Why'), el('th', null, 'Outcome')])),
        el('tbody', null, entries.slice(0, 24).map(function (e) {
          return el('tr', null, [
            el('td.mono.small', null, E.fmtDateTime(e.at)),
            el('td.small', null, e.action),
            el('td.small', null, [e.actor || '--', el('span.small.faint', null, ' ' + e.actorType)]),
            el('td.small.muted', null, e.why || '--'),
            el('td', null, chip(e.outcome, e.outcome === 'refused' ? 'is-crit' : (e.outcome === 'failed' ? 'is-warn' : 'is-plain')))
          ]);
        }))
      ])),
      foot: connectorCalls && connectorCalls.length
        ? connectorCalls.length + ' connector calls on this record, every one simulated and labelled as such.' : null
    });
  }

  /* ==================================================================== flag */

  function flag() {
    var d = E.data();
    var wrap = el('div.col');

    if (!d.holds.length) {
      wrap.appendChild(UI.empty('Nothing is held for a rehire review',
        'When an applicant matches a prior employment record marked not eligible for rehire, they appear here rather than being rejected.'));
    }

    d.holds.forEach(function (h) {
      var r = h.rehire;
      wrap.appendChild(card({
        eyebrow: 'Stopped, not rejected', title: h.candidate.name + ' matched a prior employment record',
        sub: 'The product stopped and put this in front of a person. It did not reject him, because the record might be wrong and the only way to find out is to ask somebody who was there.',
        body: el('div.col', null, [
          deflist([
            ['Previous role', r.record.role + ', ' + r.record.storeName],
            ['Employed', r.record.startedOn.slice(0, 10) + ' to ' + r.record.separatedOn.slice(0, 10)],
            ['Employee ID', r.record.employeeId],
            ['On the record', r.record.separationReason],
            ['Match confidence', r.confidence === 'exact' ? 'Exact: name, date of birth and last four phone digits all agree'
                                                          : 'Partial: name and date of birth agree, the phone number has changed'],
            ['Scope of the lookup', r.scope]
          ]),
          el('div.sim-note', null, [
            el('b', null, 'This reads one customer\'s own records and nothing else. '),
            'Pooling employment history across customers and answering questions from the pool is what a consumer reporting agency does, which is a different company under a different licence.'
          ]),
          h.review
            ? el('div.ch-note', null, 'Already reviewed: ' + h.review.outcome + ' by ' + h.review.by +
                ' on ' + E.fmtDateTime(h.review.at) + '. ' + (h.review.reason || ''))
            : el('div.row.wrap', { style: { gap: '8px' } }, [
                btn('Uphold it, and close the application', { cls: 'is-crit', onClick: function () { holdSheet(h, 'uphold'); } }),
                btn('Override it, and let this continue', { cls: 'is-primary', onClick: function () { holdSheet(h, 'override'); } })
              ])
        ])
      }));
    });

    if (d.blocked.items.length) {
      wrap.appendChild(card({
        eyebrow: 'Everything else that has stopped', title: d.blocked.count + ' open, ' + d.blocked.blocking + ' actually blocking',
        flush: true,
        body: el('div.qlist', null, d.blocked.items.map(function (x) {
          return el('button.qitem' + (x.severity === 'crit' ? '.is-crit' : '.is-warn'), {
            type: 'button',
            onclick: function () { if (x.candidate) openCandidate(x.candidate.applicationId); }
          }, [
            UI.avatar(x.candidate ? x.candidate.initials : '!', x.severity === 'crit' ? 'crit' : null),
            el('div.qmain', null, [
              el('div.qname', null, x.title),
              el('div.qsub', null, (x.candidate ? x.candidate.name + ' · ' : '') + (x.detail || '')),
              el('div.small.faint', null, 'Next: ' + (x.nextAction || 'not specified'))
            ]),
            el('div.row', { style: { gap: '6px', alignItems: 'center' } }, [
              chip(x.blocksProgress ? 'Blocking' : 'Visible only', x.blocksProgress ? 'is-crit' : 'is-plain'),
              el('span.small.mono.faint', null, E.coarse(x.openForMs))
            ])
          ]);
        }))
      }));
    }

    wrap.appendChild(card({
      eyebrow: 'Why this check exists', title: 'Speed makes this failure more likely, not less',
      body: el('p.small', null,
        'A product whose whole argument is a shorter time to hire has to be able to say what it does when moving fast would be wrong. ' +
        'This is that answer: it stops, it names what it found, and it will not proceed either way until a person decides and gives a reason.')
    }));
    return wrap;
  }

  function holdSheet(h, outcome) {
    sheet({
      eyebrow: outcome === 'override' ? 'Override' : 'Uphold',
      title: (outcome === 'override' ? 'Override the record on ' : 'Uphold the record on ') + h.candidate.name + '?',
      body: el('div.col', null, [
        el('p.small', null, outcome === 'override'
          ? 'The application continues. Your name and your reason go on the audit trail permanently.'
          : 'The application ends here. Your name and your reason go on the audit trail permanently.'),
        el('label.col.tight', null, [
          UI.eyebrow('Reason, required'),
          el('textarea.ch-input', { rows: 3, id: 'hold-reason', style: { width: '100%', minHeight: '76px' },
            placeholder: 'What did you check, and who did you ask' })
        ]),
        el('div.row', { style: { gap: '8px' } }, [
          btn('Confirm, and record it against me', {
            cls: outcome === 'override' ? 'is-primary' : 'is-crit',
            onClick: function () {
              var reason = (document.getElementById('hold-reason') || {}).value || '';
              if (!reason.trim()) { toast('A reason is required.', 'crit', 3000); return; }
              window.App.closeSheet();
              actThen(E.transition(h.brief.applicationId, outcome === 'override' ? 'ELIGIBLE' : 'INELIGIBLE',
                { reason: reason }), 'Recorded.');
            }
          }),
          btn('Cancel', { cls: 'is-ghost', onClick: function () { window.App.closeSheet(); } })
        ])
      ])
    });
  }

  /* ============================================================== compliance */

  function compliance() {
    var d = E.data();
    var wrap = el('div.col');

    if (!d.cases.length) {
      wrap.appendChild(UI.empty('No live compliance clocks',
        'Clocks appear when somebody starts work. Every one of them is derived from a date on the record and a rule with a citation.'));
      return wrap;
    }

    d.cases.forEach(function (c) {
      if (c.adverseBar) wrap.appendChild(barCard(c));
      wrap.appendChild(clocksCard(c, c.name));
      if (c.adverseProcess) wrap.appendChild(adverseCard(c));
    });

    wrap.appendChild(el('div.sim-note', null, [el('b', null, 'A caveat that is in the code too. '), d.note]));
    return wrap;
  }

  function clocksCard(c, name) {
    var clocks = c.clocks || [];
    return card({
      eyebrow: 'Deadlines', title: clocks.length + ' clocks on ' + name,
      sub: 'Every one computed from a date on the record. None of these numbers is stored.',
      body: el('div.col.tight', null, clocks.map(function (k) {
        return el('div.clock' + (k.tone !== 'clock' ? '.is-' + k.tone : ''), null, [
          el('div.clock-main', null, [
            el('div.clock-t', null, k.title),
            el('div.clock-s', null, k.state),
            el('div.clock-law', null, k.rule + '  ' + k.law)
          ]),
          el('div.col', { style: { gap: 0, alignItems: 'flex-end', flex: '0 0 auto' } }, [
            el('div.clock-v', null, k.done ? 'done' : String(k.left)),
            el('div.small.faint', null, k.done ? '' : k.unit),
            ownerChip(k.owner)
          ])
        ]);
      }))
    });
  }

  function barCard(c) {
    var bar = c.adverseBar;
    return card({
      cls: '',
      eyebrow: 'Restrictions in force', title: 'Five actions are unlawful until this case closes',
      sub: bar.rule,
      body: el('div.col.tight', null, [
        el('div.row.wrap', { style: { gap: '6px' } }, bar.barred.map(function (b) { return chip(b, 'is-crit'); })),
        el('p.small.muted', null, bar.likelyCause),
        bar.attempts.length ? el('div.col.tight', null, [
          UI.eyebrow(bar.attempts.length + ' attempts refused'),
          el('div.tw', null, el('table.t', null, [
            el('thead', null, el('tr', null, [el('th', null, 'When'), el('th', null, 'Who'), el('th', null, 'Why it was refused')])),
            el('tbody', null, bar.attempts.map(function (x) {
              return el('tr', null, [
                el('td.mono.small', null, E.fmtDateTime(x.at)),
                el('td.small', null, x.who),
                el('td.small.muted', null, x.why)
              ]);
            }))
          ]))
        ]) : el('p.small.faint', null, 'No attempts have been refused yet. Try removing her shift from the assistant.'),
        btn('Try to remove her shift', { cls: 'is-ghost is-sm', onClick: function () {
          E.tool('remove_shift', { name: c.name }, true).then(function (r) {
            toast(r.ok ? 'Removed.' : '<b>Refused.</b> ' + r.error, r.ok ? 'good' : 'crit', 7000);
            E.refresh();
          });
        } })
      ])
    });
  }

  function adverseCard(c) {
    var p = c.adverseProcess;
    return card({
      eyebrow: 'A check came back with a record on it', title: 'The pre-adverse process, owned by a person',
      sub: p.rule,
      body: el('div.col.tight', null, [
        el('p.small', null, 'Found on: ' + p.searches.join(', ') + '.'),
        el('div.col.tight', null, p.steps.map(function (s, i) {
          return el('div.row', { style: { gap: '8px', alignItems: 'center' } }, [
            el('span.step-num', null, String(i + 1)),
            el('span.small', null, s.name),
            ownerChip(s.owner),
            s.note ? el('span.small.faint', null, s.note) : null
          ]);
        })),
        el('div.sim-note', null, [el('b', null, 'Never automated. '),
          'A person reviews anything adverse individually, and no notice goes out without a person sending it.'])
      ])
    });
  }

  /* ================================================================== checks */

  function checks() {
    var d = E.data();
    var wrap = el('div.col');
    var open = d.checks.filter(function (c) { return !c.check.closedAt; });

    wrap.appendChild(stats([
      metric({ value: d.checks.length, label: 'Checks ordered', sub: 'All time in this dataset' }),
      metric({ value: open.length, label: 'Still open', sub: 'With the agency', tone: 'clock' }),
      metric({ value: d.checks.filter(function (c) { return c.check.outcome === 'adverse_possible'; }).length,
               label: 'Returned a record', sub: 'A person reviews each one', tone: 'accent' }),
      metric({ value: open.reduce(function (n, c) { return n + c.searches.filter(function (s) { return s.overdue; }).length; }, 0),
               label: 'Searches past their expected time', sub: 'The wait is the county court', tone: 'clock' })
    ]));

    wrap.appendChild(el('div.sim-note', null, [
      el('b', null, 'We order and track. We never perform a check. '),
      'The screening agency is a simulated adapter here, and there is no national criminal database available to employers, which is why the county rows exist at all.'
    ]));

    wrap.appendChild(card({
      eyebrow: 'Orders', title: d.checks.length + ' background checks', flush: true,
      body: d.checks.length
        ? el('div.qlist', null, d.checks.map(function (c) {
            var openS = c.searches.filter(function (s) { return !s.returnedAt; });
            return el('button.qitem' + (openS.some(function (s) { return s.overdue; }) ? '.is-warn' : ''), {
              type: 'button', onclick: function () { openCheck(c); }
            }, [
              UI.avatar(c.initials),
              el('div.qmain', null, [
                el('div.qname', null, c.name),
                el('div.qsub', null, c.searches.length + ' searches, ' + openS.length + ' still open · ordered ' +
                  E.fmtDateTime(c.check.orderedAt) + ' · ref ' + c.check.externalRef)
              ]),
              el('div.row', { style: { gap: '6px', alignItems: 'center' } }, [
                c.check.closedAt
                  ? chip(c.check.outcome === 'clear' ? 'Clear' : 'Record found',
                         c.check.outcome === 'clear' ? 'is-good' : 'is-crit')
                  : chip('Open', 'own-clock', true),
                el('span.small.mono.faint', null, E.coarse(c.openForMs))
              ])
            ]);
          }))
        : UI.empty('No checks ordered yet')
    }));

    wrap.appendChild(card({
      eyebrow: 'The legal position', title: 'Why an adverse result cannot be collapsed',
      body: el('p.small', null, d.law),
      foot: 'The agent: ' + d.agentDoes + '  A person: ' + d.humanDoes
    }));
    return wrap;
  }

  function openCheck(c) {
    sheet({
      eyebrow: 'Background check', title: c.name,
      chipNode: chip(c.check.mode, 'is-plain'),
      body: el('div.col', null, [
        card({
          body: deflist([
            ['Ordered', E.fmtDateTime(c.check.orderedAt)],
            ['Ordered by', c.check.orderedBy],
            ['Agency reference', c.check.externalRef],
            ['Mode', c.check.mode + ', no real agency was contacted'],
            ['Open for', E.dur(c.openForMs)],
            ['Outcome', c.check.outcome || 'still running']
          ])
        }),
        card({
          eyebrow: 'By search', title: 'Which one is actually holding it up', flush: true,
          body: el('div.tw', null, el('table.t', null, [
            el('thead', null, el('tr', null, [el('th', null, 'Search'), el('th', null, 'Venue'),
              el('th', null, 'Elapsed'), el('th', null, 'Result')])),
            el('tbody', null, c.searches.map(function (s) {
              return el('tr', null, [
                el('td.small', null, [s.name, s.note ? el('div.small.faint', null, s.note) : null]),
                el('td.small.muted', null, s.venue),
                el('td.mono.small' + (s.overdue ? '' : ''), { style: s.overdue ? { color: 'var(--warn)' } : null },
                  E.dur(s.elapsedMs)),
                el('td', null, s.returnedAt
                  ? chip(s.result === 'clear' ? 'Clear' : 'Record found', s.result === 'clear' ? 'is-good' : 'is-crit')
                  : chip(s.overdue ? 'Past expected' : 'Pending', s.overdue ? 'is-warn' : 'own-clock'))
              ]);
            }))
          ]))
        }),
        c.check.disclosure ? card({
          eyebrow: 'FCRA', title: 'The disclosure and the authorisation are two documents',
          body: el('p.small', null, c.check.disclosure.rule)
        }) : null
      ])
    });
  }

  /* ================================================================== funnel */

  function funnel() {
    var d = E.data();
    var r = d.rollup;
    var wrap = el('div.col');

    wrap.appendChild(el('div.sim-note', null, [
      el('b', null, 'Nothing on this screen was typed in. '),
      'Every figure is computed from recorded events. If the data produces an ugly number, the ugly number is what appears.'
    ]));

    wrap.appendChild(stats([
      metric({ value: r.applications, label: 'Applications', sub: r.open + ' still open' }),
      metric({ value: r.started, label: 'Reached a first day', sub: 'Measured, not projected' }),
      metric({ value: r.lost, label: 'Lost', sub: Object.keys(r.lostBreakdown).map(function (k) {
        return r.lostBreakdown[k] + ' ' + k.toLowerCase().replace(/_/g, ' '); }).join(', ') || 'none', tone: 'accent' }),
      metric({ value: r.queue.queueShare * 100, dp: 1, unit: '%', label: 'Of elapsed time, queued',
               sub: 'Rather than worked', tone: 'clock' })
    ]));

    wrap.appendChild(card({
      eyebrow: 'Timings', title: 'Application to first shift, and every leg of it',
      sub: 'Median, with n. A median of two is not a median and the screen says so.',
      body: deflist([
        ['Application to screening', span(r.spans.applicationToScreening)],
        ['Screening to decision', span(r.spans.screeningToDecision)],
        ['Decision to offer sent', span(r.spans.decisionToOffer)],
        ['Offer to acceptance', span(r.spans.offerToAcceptance)],
        ['Acceptance to first shift', span(r.spans.acceptanceToFirstShift)],
        ['Application to offer', span(r.spans.applicationToOffer)],
        ['Application to first shift', span(r.spans.applicationToFirstShift)],
        ['Application to first day worked', span(r.spans.applicationToStart)]
      ])
    }));

    wrap.appendChild(card({
      eyebrow: 'Where the time goes', title: d.bottleneck.steps.length ? 'Ranked by total queue time' : 'Not enough history yet',
      sub: 'Separating what we can act on from what we cannot.',
      flush: true,
      body: el('div.bars', null, d.bottleneck.steps.map(function (s) {
        var max = d.bottleneck.steps[0].queueMs || 1;
        return UI.bar({
          label: s.n + '. ' + s.name,
          pct: (s.queueMs / max) * 100,
          value: E.dur(s.queueMs),
          color: s.actability === 'external' ? 'var(--clock)'
            : (s.actability === 'person' ? 'var(--accent)' : 'var(--system)')
        });
      })),
      foot: 'Amber is a wait outside our control. Blue is a queue in front of a person, which is the kind this product removes.'
    }));

    wrap.appendChild(card({
      eyebrow: 'Who acted', title: E.n(d.actors.reduce(function (n, a) { return n + a.actions; }, 0)) + ' recorded actions',
      flush: true,
      body: el('div.bars', null, d.actors.map(function (a) {
        return UI.bar({ label: a.actorType, pct: a.pct, value: E.pct(a.pct),
          color: a.actorType === 'agent' ? 'var(--agent)' : a.actorType === 'human' ? 'var(--accent)'
            : a.actorType === 'external' ? 'var(--clock)' : 'var(--system)' });
      }))
    }));

    wrap.appendChild(card({
      eyebrow: 'Across stores', title: 'Cross-store comparison',
      sub: 'A store manager cannot use this. A district manager or field HR can, which is the only reason it is here.',
      flush: true,
      body: el('div.tw', null, el('table.t', null, [
        el('thead', null, el('tr', null, [el('th', null, 'Store'), el('th', null, 'Manager'),
          el('th', null, 'Applications'), el('th', null, 'Started'),
          el('th', null, 'App to offer'), el('th', null, 'Queue share')])),
        el('tbody', null, d.stores.map(function (s) {
          return el('tr', null, [
            el('td.small', null, s.storeName),
            el('td.small.muted', null, s.manager),
            el('td.num', null, String(s.applications)),
            el('td.num', null, String(s.started)),
            el('td.num.mono', null, s.spans.applicationToOffer.median == null ? '--'
              : E.dur(s.spans.applicationToOffer.median)),
            el('td.num.mono', null, s.queue.queueShare == null ? '--' : E.pct(s.queue.queueShare * 100))
          ]);
        }))
      ]))
    }));

    wrap.appendChild(card({
      eyebrow: 'Stage detail', title: 'All 20 stages', flush: true,
      body: el('div.steps', null, [stepHead()].concat(d.funnel.map(function (s) {
        return el('div.step.' + E.ownerClass(s.owner), null, [
          el('div.step-num', null, String(s.n)),
          el('div.step-name', null, s.name),
          el('div.step-cell', null, ownerChip(s.owner)),
          el('div.step-cell.num', null, String(s.entered)),
          el('div.step-cell.num', null, s.lost ? E.pct(s.dropPct) : el('span.faint', null, '--')),
          el('div.step-cell.num.mono', null, s.medianMs == null ? el('span.faint', null, 'no data') : E.dur(s.medianMs))
        ]);
      })))
    }));
    return wrap;
  }

  /* =================================================================== store */

  function store() {
    var d = E.data();
    var wrap = el('div.col');
    var m = d.metrics;

    wrap.appendChild(el('div.row.wrap', { style: { gap: 'var(--s3)', alignItems: 'center' } }, [
      el('div.col', { style: { gap: 0, flex: '1 1 auto' } }, [
        el('h2.h2', null, d.store.name),
        el('div.small.muted', null, d.store.city + ', ' + d.store.state + ' · ' + d.store.manager +
          ' · ' + d.store.headcount + ' on the payroll')
      ]),
      el('select.btn.is-ghost.is-sm', {
        'aria-label': 'Choose a store',
        onchange: function (e) { E.ui.storeId = e.target.value; E.refresh(); }
      }, d.stores.map(function (s) {
        return el('option', { value: s.id, selected: s.id === d.store.id ? 'selected' : null }, s.name);
      }))
    ]));

    wrap.appendChild(stats([
      metric({ value: m.applications, label: 'Applications', sub: m.open + ' open' }),
      metric({ value: m.started, label: 'Started work', sub: 'In this dataset' }),
      metric({ value: d.openings.reduce(function (n, o) { return n + o.openings; }, 0),
               label: 'Positions open', sub: d.openings.length + ' requisitions' }),
      /* Was 'First shifts this week' with the sub 'Placed and confirmed'. The
         server's seven-day window was removed on 7 Sep 2026 and this payload is
         now every shift ever recorded at the store, so both claims were false.
         The view is the thing that knows the present, so it counts what is
         actually ahead. */
      metric({ value: d.shifts.length, label: 'First shifts placed',
               sub: (function () {
                 var ahead = d.shifts.filter(function (s) { return s.inMs > 0; }).length;
                 return ahead === d.shifts.length ? 'All still ahead'
                      : ahead ? ahead + ' still ahead' : 'All already worked';
               })(), tone: 'accent' })
    ]));

    wrap.appendChild(card({
      eyebrow: 'Requisitions', title: 'Open positions at this store', flush: true,
      body: el('div.tw', null, el('table.t', null, [
        el('thead', null, el('tr', null, [el('th', null, 'Role'), el('th', null, 'Positions'),
          el('th', null, 'Rate'), el('th', null, 'Applications'), el('th', null, 'In flight'),
          el('th', null, 'Hired'), el('th', null, 'Open for')])),
        el('tbody', null, d.openings.map(function (o) {
          return el('tr', null, [
            el('td.small', null, o.title),
            el('td.num', null, String(o.openings)),
            el('td.num.mono', null, E.money(o.rateCents)),
            el('td.num', null, String(o.applications)),
            el('td.num', null, String(o.inFlight)),
            el('td.num', null, String(o.hired)),
            el('td.num.mono', null, E.dur(o.openForMs))
          ]);
        }))
      ])),
      foot: 'Counts are positions, not candidates. A requisition can carry more than one opening.'
    }));

    if (d.restrictions.length) {
      wrap.appendChild(card({
        eyebrow: 'Employment restrictions', title: 'Rules in force at this store', flush: true,
        body: el('div.qlist', null, d.restrictions.map(function (r) {
          return el('div.qitem.is-crit', { style: { cursor: 'default', gridTemplateColumns: 'minmax(0,1fr) auto' } }, [
            el('div.qmain', null, [
              el('div.qname', null, r.name),
              el('div.qsub', null, r.why),
              el('div.row.wrap', { style: { gap: '4px', marginTop: '4px' } },
                r.barred.map(function (b) { return chip(b, 'is-crit'); }))
            ]),
            chip('In force', 'is-crit')
          ]);
        }))
      }));
    }

    wrap.appendChild(card({
      eyebrow: 'First shifts', title: (function () {
        var ahead = d.shifts.filter(function (s) { return s.inMs > 0; }).length;
        if (!d.shifts.length) return 'No first shifts placed';
        if (ahead === d.shifts.length) return d.shifts.length + ' placed, all still ahead';
        if (!ahead) return d.shifts.length + ' placed, all already worked';
        return d.shifts.length + ' placed, ' + ahead + ' still ahead';
      })(), flush: true,
      body: d.shifts.length
        ? el('div.qlist', null, d.shifts.map(function (s) {
            return el('button.qitem', { type: 'button', onclick: function () { openCandidate(s.applicationId); } }, [
              UI.avatar(s.initials),
              el('div.qmain', null, [
                el('div.qname', null, s.name),
                el('div.qsub', null, E.fmtDay(s.startsAt) + ' · ' +
                  (s.inMs > 0 ? 'ahead' : 'already worked') + ' · ' + s.noticeDays + ' days notice' +
                  (s.premiumPayable ? ' · inside the fair workweek window, a premium is payable' : ''))
              ]),
              chip(s.confirmState === 'confirmed' ? 'Confirmed by them' : 'Not confirmed',
                   s.confirmState === 'confirmed' ? 'is-good' : 'is-warn')
            ]);
          }))
        : UI.empty('No first shifts placed')
    }));

    wrap.appendChild(card({
      eyebrow: 'District', title: 'The same measures across every store',
      sub: 'The one screen in this product aimed at somebody other than the person doing the hiring.',
      flush: true,
      body: el('div.tw', null, el('table.t', null, [
        el('thead', null, el('tr', null, [el('th', null, 'Store'), el('th', null, 'Applications'),
          el('th', null, 'Open'), el('th', null, 'Started'), el('th', null, 'App to offer')])),
        el('tbody', null, d.comparison.map(function (s) {
          return el('tr', null, [
            el('td.small', null, s.storeName),
            el('td.num', null, String(s.applications)),
            el('td.num', null, String(s.open)),
            el('td.num', null, String(s.started)),
            el('td.num.mono', null, s.spans.applicationToOffer.median == null ? '--'
              : E.dur(s.spans.applicationToOffer.median))
          ]);
        }))
      ]))
    }));
    return wrap;
  }

  /* ================================================================= sources */

  function sources() {
    var d = E.data();
    var wrap = el('div.col');

    wrap.appendChild(el('div.sim-note', null, [
      el('b', null, 'Every destination below is a simulated connector. '),
      'None of them holds a credential and none of them names a vendor we have integrated. The point of the screen is the shape: a request goes out, it takes time, it can fail, and a failure is retryable or it is not.'
    ]));

    wrap.appendChild(card({
      eyebrow: 'Outbound', title: 'Where the openings are posted', flush: true,
      body: el('div.tw', null, el('table.t', null, [
        el('thead', null, el('tr', null, [el('th', null, 'Destination'), el('th', null, 'Attempts'),
          el('th', null, 'Accepted'), el('th', null, 'Failed'), el('th', null, 'Last error')])),
        el('tbody', null, d.outbound.map(function (o) {
          return el('tr', null, [
            /* The column was headed "Live" and read `o.live` until 8 Sep 2026.
               The server renamed that field to `accepted` on 7 September and
               this was not changed with it, so every row printed the literal
               word "undefined". `accepted` counts simulated calls that
               returned ok, which is not a live listing, so the destination
               cell says so rather than leaving the table to imply it. */
            el('td.small', null, [o.destination,
              o.connected ? null : el('span.muted', null, ' · not connected')]),
            el('td.num', null, String(o.attempts)),
            el('td.num', null, String(o.accepted)),
            el('td.num', null, o.failed ? el('span', { style: { color: 'var(--crit)' } }, String(o.failed)) : '0'),
            el('td.small.muted', null, o.lastError || '--')
          ]);
        }).concat(d.closed.map(function (c) {
          return el('tr', null, [
            el('td.small', null, c.destination),
            el('td.num.faint', null, '--'),
            el('td', null, chip(c.status, 'is-crit')),
            el('td.num.faint', null, '--'),
            el('td.small.muted', null, c.why)
          ]);
        })))
      ])),
      foot: 'The failed post and its retry are left in on purpose. An integration surface with no errors in it has never been near a real vendor.'
    }));

    wrap.appendChild(card({
      eyebrow: 'Inbound', title: 'Where the people actually came from', flush: true,
      sub: 'Counted from the source recorded on each application.',
      body: el('div.tw', null, el('table.t', null, [
        el('thead', null, el('tr', null, [el('th', null, 'Source'), el('th', null, 'Kind'),
          el('th', null, 'Applications'), el('th', null, 'Reached a decision'), el('th', null, 'Started'),
          el('th', null, 'Failed eligibility')])),
        el('tbody', null, d.inbound.map(function (s) {
          return el('tr', null, [
            el('td.small', null, s.source),
            el('td', null, chip(s.kind, 'is-plain')),
            el('td.num', null, String(s.applications)),
            el('td.num', null, String(s.advanced)),
            el('td.num', null, String(s.hired)),
            el('td.num', null, String(s.ineligible))
          ]);
        }))
      ]))
    }));

    wrap.appendChild(card({
      eyebrow: 'People this retailer already knows', title: d.identity.matchedPriorEmployee + ' of ' +
        d.identity.applications + ' applicants have worked here before',
      sub: d.identity.scope,
      flush: true,
      body: d.identity.matches.length
        ? el('div.tw', null, el('table.t', null, [
            el('thead', null, el('tr', null, [el('th', null, 'Applicant'), el('th', null, 'Match'),
              el('th', null, 'Previous role'), el('th', null, 'Rehire eligible'), el('th', null, 'I-9 reuse')])),
            el('tbody', null, d.identity.matches.map(function (m) {
              return el('tr', null, [
                el('td.small', null, m.name),
                el('td', null, chip(m.confidence, m.confidence === 'exact' ? 'is-good' : 'is-warn')),
                el('td.small.muted', null, m.priorRole),
                el('td', null, chip(m.rehireEligible ? 'Yes' : 'No', m.rehireEligible ? 'is-good' : 'is-crit')),
                el('td.small.muted', null, m.i9Reusable ? 'Inside the three-year window' : 'A new form is needed')
              ]);
            }))
          ]))
        : UI.empty('No applicant matched a prior employment record')
    }));

    wrap.appendChild(card({
      eyebrow: 'The records being read', title: d.known.length + ' prior employees on file',
      sub: 'This customer\'s own records. Nothing is matched across customers.',
      flush: true,
      body: el('div.tw', null, el('table.t', null, [
        el('thead', null, el('tr', null, [el('th', null, 'Name'), el('th', null, 'Role'), el('th', null, 'Store'),
          el('th', null, 'Left'), el('th', null, 'Rehire eligible'), el('th', null, 'Training held')])),
        el('tbody', null, d.known.map(function (k) {
          return el('tr', null, [
            el('td.small', null, k.name),
            el('td.small.muted', null, k.role),
            el('td.small.muted', null, k.storeName),
            el('td.mono.small', null, k.separatedOn.slice(0, 10)),
            el('td', null, chip(k.rehireEligible ? 'Yes' : 'No', k.rehireEligible ? 'is-good' : 'is-crit')),
            el('td.num', null, String(k.trainingHeld))
          ]);
        }))
      ]))
    }));
    return wrap;
  }

  /* ------------------------------------------------------------- registry -- */

  return {
    deck:       { title: 'Today', sub: 'Applications and actions waiting on you', icon: 'deck', render: deck },
    pipeline:   { title: 'Pipeline', sub: 'All 20 steps, counted from recorded events', icon: 'pipeline', render: pipeline },
    candidate:  { title: 'Candidate record', sub: 'One person, the whole journey', icon: 'person', render: candidate },
    screening:  { title: 'Screening', sub: 'Transcripts, evaluations and the phrase bank', icon: 'chat', render: screening },
    decide:     { title: 'Approvals', sub: 'Candidates awaiting a hire decision', icon: 'decide', render: decide },
    flag:       { title: 'Exceptions', sub: 'Everything that stopped, and why', icon: 'flag', render: flag },
    compliance: { title: 'Compliance', sub: 'I-9, E-Verify and adverse action', icon: 'shield', render: compliance },
    checks:     { title: 'Background checks', sub: 'Order status by search and county', icon: 'clock', render: checks },
    funnel:     { title: 'Reports', sub: 'Measured from events, never written in', icon: 'chart', render: funnel },
    store:      { title: 'Store view', sub: 'One store, and the district around it', icon: 'store', render: store },
    sources:    { title: 'Sources', sub: 'Where openings go out and people come in', icon: 'globe', render: sources }
  };
})();
