/* ============================================================================
   llm.js  ·  the model boundary

   One place where a model is called. Everything else in the product asks this
   file and gets structured JSON back.

   Configuration, from the environment and never from the browser:

     LLM_PROVIDER   anthropic | openai | none      default anthropic
     LLM_API_KEY    left blank on purpose today
     LLM_MODEL      default claude-sonnet-5
     LLM_BASE_URL   optional, for an OpenAI-compatible endpoint
     LLM_TIMEOUT_MS default 45000

   WITH NO KEY THE PRODUCT STILL RUNS. What it does instead is a deterministic
   rubric match against the phrase bank the customer owns. That is a real thing
   the product does and it is genuinely useful, but it is NOT a model, and every
   result it produces is stamped provider:'none', mode:'deterministic-fallback'
   and carries the sentence "No model ran." The interface prints that sentence.
   Calling a fallback an LLM result is the exact failure this file exists to
   prevent.

   The key is read here, in the server process. It is never included in any API
   response. /api/llm/status returns whether a key is configured and which model
   would be used, and nothing else.

   Chain of thought is not requested and not stored. The evaluation, the
   evidence quoted from the transcript, the concerns and the confidence are.
   ============================================================================ */

'use strict';

const PROMPT_VERSION = 'screening-eval-1.2.0';

function config() {
  const provider = (process.env.LLM_PROVIDER || 'anthropic').toLowerCase();
  const apiKey = process.env.LLM_API_KEY || '';
  return {
    provider: apiKey ? provider : 'none',
    configuredProvider: provider,
    hasKey: !!apiKey,
    apiKey,
    model: process.env.LLM_MODEL || (provider === 'openai' ? 'gpt-4.1' : 'claude-sonnet-5'),
    baseUrl: process.env.LLM_BASE_URL || (provider === 'openai'
      ? 'https://api.openai.com/v1'
      : 'https://api.anthropic.com/v1'),
    timeoutMs: Number(process.env.LLM_TIMEOUT_MS || 45000),
    maxTokens: Number(process.env.LLM_MAX_TOKENS || 2000)
  };
}

/** Safe to hand to the browser. Deliberately contains no key and no fragment of one. */
function publicStatus() {
  const c = config();
  return {
    configured: c.hasKey,
    provider: c.provider,
    configuredProvider: c.configuredProvider,
    model: c.hasKey ? c.model : null,
    fallback: c.hasKey ? null : 'deterministic-rubric',
    note: c.hasKey
      ? 'Screening evaluations are generated by ' + c.model + '.'
      : 'No LLM_API_KEY is set. Screening evaluations come from a deterministic rubric match against the phrase bank. No model runs.'
  };
}

/* ------------------------------------------------------------ the schema ---
   The shape every screening evaluation must have. Passed to the provider as a
   tool schema so the model is forced into it rather than asked politely.

   Note what is NOT in the recommendation enum: there is no reject. The agent
   may advance somebody to a person, or ask a person to look. It cannot end an
   application. That is a product rule and it is also the reason this enum is
   the shape it is.
   ------------------------------------------------------------------------- */

const EVAL_SCHEMA = {
  type: 'object',
  properties: {
    recommendation: {
      type: 'string',
      enum: ['advance', 'review', 'insufficient_evidence'],
      description: 'advance: the transcript supports moving to a hiring decision. review: a person should look at a specific concern first. insufficient_evidence: the conversation did not cover enough to say. There is deliberately no reject value. Only a person may reject.'
    },
    summary: { type: 'string', description: 'Two sentences at most, for a manager with 40 seconds.' },
    criteria: {
      type: 'array',
      description: 'One entry per criterion supplied in the job requirements. Do not invent criteria.',
      items: {
        type: 'object',
        properties: {
          key: { type: 'string' },
          verdict: { type: 'string', enum: ['met', 'partly_met', 'not_met', 'not_covered'] },
          evidence: { type: 'string', description: 'Quoted from the transcript. Empty string if not covered.' },
          note: { type: 'string' }
        },
        required: ['key', 'verdict', 'evidence']
      }
    },
    concerns: {
      type: 'array',
      items: {
        type: 'object',
        properties: {
          concern: { type: 'string' },
          evidence: { type: 'string' },
          severity: { type: 'string', enum: ['low', 'medium', 'high'] }
        },
        required: ['concern', 'evidence', 'severity']
      }
    },
    unansweredQuestions: { type: 'array', items: { type: 'string' } },
    confidence: { type: 'number', description: '0 to 1. Low when the transcript is short or evasive.' },
    recommendedNextAction: { type: 'string' }
  },
  required: ['recommendation', 'summary', 'criteria', 'concerns', 'unansweredQuestions', 'confidence', 'recommendedNextAction']
};

const SYSTEM = [
  'You evaluate a recorded screening conversation for an hourly frontline retail role in the United States.',
  '',
  'Rules you must follow.',
  '1. You are producing a recommendation and evidence for a human manager. You are not making a hiring decision. A person decides.',
  '2. Every criterion verdict must be supported by something the candidate actually said. Quote it. If they did not cover it, mark it not_covered and leave the evidence empty. Never infer an answer that is not there.',
  '3. Do not assess anything about age, national origin, disability, religion, sex, pregnancy, arrest or conviction history, credit, or family status. If the transcript raises one of these, ignore it for scoring and list it as a concern of severity high describing only that a protected topic was raised.',
  '4. Eligibility has already been decided by deterministic rules and is given to you as fact. Do not re-decide it and do not contradict it.',
  '5. If the transcript is too short or too evasive to judge, say so with recommendation insufficient_evidence rather than guessing.',
  '6. Give the evaluation only. Do not explain your reasoning process.'
].join('\n');

function buildPrompt(input) {
  const lines = [];
  lines.push('# Role');
  lines.push(input.role.title + ' at ' + input.role.storeName + '. ' + input.role.summary);
  lines.push('');
  lines.push('# Criteria to evaluate, and nothing else');
  input.role.criteria.forEach((c) => lines.push('- ' + c.key + ': ' + c.description));
  lines.push('');
  lines.push('# Eligibility, already decided by deterministic rules. Treat as fact.');
  input.eligibility.results.forEach((r) => {
    lines.push('- ' + r.name + ': ' + (r.passed ? 'pass' : 'fail') + '. ' + r.basis);
  });
  lines.push('');
  lines.push('# Candidate');
  lines.push('Applied ' + input.candidate.appliedAt + ' via ' + input.candidate.source + '.');
  if (input.candidate.priorEmployment) lines.push('Prior employment with this retailer: ' + input.candidate.priorEmployment);
  lines.push('Stated experience: ' + (input.candidate.experience || 'none stated'));
  lines.push('');
  lines.push('# Transcript');
  input.transcript.forEach((t) => lines.push(t.speaker + ': ' + t.text));
  return lines.join('\n');
}

/* ------------------------------------------------------------- providers --- */

async function callAnthropic(cfg, system, prompt, schema, toolName) {
  const res = await fetchJSON(cfg, cfg.baseUrl + '/messages', {
    'x-api-key': cfg.apiKey,
    'anthropic-version': '2023-06-01',
    'content-type': 'application/json'
  }, {
    model: cfg.model,
    max_tokens: cfg.maxTokens,
    system,
    tools: [{ name: toolName, description: 'Return the evaluation.', input_schema: schema }],
    tool_choice: { type: 'tool', name: toolName },
    messages: [{ role: 'user', content: prompt }]
  });

  const block = (res.body.content || []).find((b) => b.type === 'tool_use');
  if (!block) throw new Error('provider returned no tool_use block');
  return { data: block.input, usage: res.body.usage || null, raw: { id: res.body.id, model: res.body.model } };
}

async function callOpenAI(cfg, system, prompt, schema, toolName) {
  const res = await fetchJSON(cfg, cfg.baseUrl + '/chat/completions', {
    authorization: 'Bearer ' + cfg.apiKey,
    'content-type': 'application/json'
  }, {
    model: cfg.model,
    max_tokens: cfg.maxTokens,
    messages: [{ role: 'system', content: system }, { role: 'user', content: prompt }],
    tools: [{ type: 'function', function: { name: toolName, parameters: schema } }],
    tool_choice: { type: 'function', function: { name: toolName } }
  });

  const call = (((res.body.choices || [])[0] || {}).message || {}).tool_calls;
  if (!call || !call[0]) throw new Error('provider returned no tool call');
  return { data: JSON.parse(call[0].function.arguments), usage: res.body.usage || null,
           raw: { id: res.body.id, model: res.body.model } };
}

async function fetchJSON(cfg, url, headers, body) {
  const ctrl = new AbortController();
  const timer = setTimeout(() => ctrl.abort(), cfg.timeoutMs);
  try {
    const r = await fetch(url, { method: 'POST', headers, body: JSON.stringify(body), signal: ctrl.signal });
    const text = await r.text();
    let parsed;
    try { parsed = JSON.parse(text); }
    catch (e) { throw new Error('provider returned non-JSON, HTTP ' + r.status + ': ' + text.slice(0, 200)); }
    if (!r.ok) {
      const msg = (parsed.error && (parsed.error.message || parsed.error.type)) || ('HTTP ' + r.status);
      throw new Error('provider error: ' + msg);
    }
    return { body: parsed };
  } catch (err) {
    if (err.name === 'AbortError') throw new Error('provider timed out after ' + cfg.timeoutMs + 'ms');
    throw err;
  } finally {
    clearTimeout(timer);
  }
}

/* -------------------------------------------------------------- validate --- */

/**
 * A provider can return JSON that parses and is still wrong. Everything that
 * reaches the rest of the product goes through here first, and anything that
 * fails is an error rather than a half-populated evaluation.
 */
function validateEvaluation(data, criteriaKeys) {
  const errs = [];
  if (!data || typeof data !== 'object') return { ok: false, errors: ['not an object'] };

  const rec = data.recommendation;
  if (['advance', 'review', 'insufficient_evidence'].indexOf(rec) < 0) {
    errs.push('recommendation must be advance, review or insufficient_evidence, got ' + JSON.stringify(rec));
  }
  if (typeof data.summary !== 'string' || !data.summary.trim()) errs.push('summary missing');
  if (!Array.isArray(data.criteria)) errs.push('criteria missing');
  if (!Array.isArray(data.concerns)) errs.push('concerns missing');
  if (!Array.isArray(data.unansweredQuestions)) errs.push('unansweredQuestions missing');
  if (typeof data.confidence !== 'number' || data.confidence < 0 || data.confidence > 1) {
    errs.push('confidence must be a number between 0 and 1');
  }
  if (typeof data.recommendedNextAction !== 'string') errs.push('recommendedNextAction missing');

  if (Array.isArray(data.criteria)) {
    const invented = data.criteria.map((c) => c.key).filter((k) => criteriaKeys.indexOf(k) < 0);
    // A model inventing a criterion is the failure that matters most here,
    // because it reads as a real assessment of something nobody asked about.
    if (invented.length) errs.push('criteria not in the job requirements: ' + invented.join(', '));
    data.criteria.forEach((c, i) => {
      if (['met', 'partly_met', 'not_met', 'not_covered'].indexOf(c.verdict) < 0) {
        errs.push('criteria[' + i + '].verdict invalid: ' + JSON.stringify(c.verdict));
      }
    });
  }
  return { ok: errs.length === 0, errors: errs };
}

/* --------------------------------------------------------- the entry point - */

/**
 * Returns { ok, mode, provider, model, promptVersion, latencyMs, data, error }.
 * mode is 'llm' when a model produced the result and 'deterministic-fallback'
 * when one did not. Callers must not collapse the two.
 */
async function evaluateScreening(input, fallbackFn, opts) {
  opts = opts || {};
  const cfg = config();
  const started = Date.now();
  const criteriaKeys = input.role.criteria.map((c) => c.key);

  /* forceFallback exists for one caller: the seed. Replaying thirty-six people
     through the workflow at boot would otherwise fire thirty-odd model calls
     before anybody had asked for anything, which is slow, costs money and makes
     a fresh boot non-deterministic. */
  if (opts.forceFallback || !cfg.hasKey || cfg.configuredProvider === 'none') {
    const data = fallbackFn(input);
    return {
      ok: true, mode: 'deterministic-fallback', provider: 'none', model: null,
      promptVersion: 'rubric-1.0.0', latencyMs: Date.now() - started,
      data, error: null,
      note: 'No model ran. This evaluation is a deterministic match against the phrase bank the customer owns.' +
            (opts.forceFallback && cfg.hasKey
              ? ' Seeded evaluations always use the rubric so a fresh boot costs nothing. Run a screening from the interface to use ' + cfg.model + '.'
              : '')
    };
  }

  const system = SYSTEM;
  const prompt = buildPrompt(input);

  try {
    const fn = cfg.configuredProvider === 'openai' ? callOpenAI : callAnthropic;
    const out = await fn(cfg, system, prompt, EVAL_SCHEMA, 'record_screening_evaluation');
    const v = validateEvaluation(out.data, criteriaKeys);
    if (!v.ok) {
      return {
        ok: false, mode: 'llm', provider: cfg.configuredProvider, model: cfg.model,
        promptVersion: PROMPT_VERSION, latencyMs: Date.now() - started,
        data: null, error: 'malformed evaluation: ' + v.errors.join('; '),
        note: 'The model replied but the reply did not match the required shape, so it was rejected rather than shown.'
      };
    }
    return {
      ok: true, mode: 'llm', provider: cfg.configuredProvider, model: cfg.model,
      promptVersion: PROMPT_VERSION, latencyMs: Date.now() - started,
      data: out.data, usage: out.usage, error: null, note: null
    };
  } catch (err) {
    return {
      ok: false, mode: 'llm', provider: cfg.configuredProvider, model: cfg.model,
      promptVersion: PROMPT_VERSION, latencyMs: Date.now() - started,
      data: null, error: String(err.message || err),
      note: 'The model call failed. Nothing was written to the candidate record beyond this error.'
    };
  }
}

/* ------------------------------------------------- free-form assistant use -
   The assistant uses tool calling rather than prose generation for anything
   that touches data. This is here for the one thing that genuinely needs
   language: turning a set of tool results into a sentence.
   ------------------------------------------------------------------------- */

async function chat(system, messages, tools) {
  const cfg = config();
  if (!cfg.hasKey) return { ok: false, mode: 'none', error: 'no key configured' };
  const started = Date.now();
  try {
    if (cfg.configuredProvider === 'openai') {
      const res = await fetchJSON(cfg, cfg.baseUrl + '/chat/completions', {
        authorization: 'Bearer ' + cfg.apiKey, 'content-type': 'application/json'
      }, {
        model: cfg.model, max_tokens: cfg.maxTokens,
        messages: [{ role: 'system', content: system }].concat(messages),
        tools: (tools || []).map((t) => ({ type: 'function', function: { name: t.name, description: t.description, parameters: t.input_schema } }))
      });
      const m = ((res.body.choices || [])[0] || {}).message || {};
      return { ok: true, mode: 'llm', provider: 'openai', model: cfg.model, latencyMs: Date.now() - started,
               text: m.content || '', toolCalls: (m.tool_calls || []).map((c) => ({ name: c.function.name, args: JSON.parse(c.function.arguments) })) };
    }
    const res = await fetchJSON(cfg, cfg.baseUrl + '/messages', {
      'x-api-key': cfg.apiKey, 'anthropic-version': '2023-06-01', 'content-type': 'application/json'
    }, {
      model: cfg.model, max_tokens: cfg.maxTokens, system,
      tools: tools || [], messages
    });
    const content = res.body.content || [];
    return {
      ok: true, mode: 'llm', provider: 'anthropic', model: cfg.model, latencyMs: Date.now() - started,
      text: content.filter((b) => b.type === 'text').map((b) => b.text).join('\n').trim(),
      toolCalls: content.filter((b) => b.type === 'tool_use').map((b) => ({ id: b.id, name: b.name, args: b.input })),
      stopReason: res.body.stop_reason
    };
  } catch (err) {
    return { ok: false, mode: 'llm', provider: cfg.configuredProvider, model: cfg.model,
             latencyMs: Date.now() - started, error: String(err.message || err) };
  }
}

module.exports = {
  config, publicStatus, evaluateScreening, chat,
  validateEvaluation, buildPrompt, EVAL_SCHEMA, SYSTEM, PROMPT_VERSION
};
